"""empty message

Revision ID: 1fbfbd049b4
Revises: 390d7168ed5
Create Date: 2016-01-22 23:01:15.898415

"""

# revision identifiers, used by Alembic.
revision = '1fbfbd049b4'
down_revision = '390d7168ed5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.String(length=300), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_hash')
    ### end Alembic commands ###
