"""empty message

Revision ID: 2ef83e4c423
Revises: 81d730bb63
Create Date: 2016-01-06 19:51:53.822305

"""

# revision identifiers, used by Alembic.
revision = '2ef83e4c423'
down_revision = '81d730bb63'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match', 'team0_score')
    op.drop_column('match', 'team1_score')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('team1_score', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('match', sa.Column('team0_score', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    ### end Alembic commands ###
