"""empty message

Revision ID: aa8faaf90e
Revises: 188f9d0871a
Create Date: 2016-01-06 20:15:47.824197

"""

# revision identifiers, used by Alembic.
revision = 'aa8faaf90e'
down_revision = '188f9d0871a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match', 'completed')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('completed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    ### end Alembic commands ###
